### ISSUE TITLE
Дока и контроль сложности

### ISSUE THREAD

**Issue by hexode** [yandex-ui/noscript#113]
Кодовая база растет. С ней растет и сложность проекта. Хотелось бы, чтобы дока росла вместе с ним. Лучше итеративно, по кусочкам понимать проект, чтобы когда пришло время не было бы мучительно больно.

И кстати дока позволит задавать сфокусированые вопросы по проекту, что я думаю на такой стадии развития очень для него выгодно.

По поводу контроля сложности есть ли возможность прикрутить это к прооекту https://github.com/jsoverson/plato. Мне кажется это очень крутая штука.

**Comment by Katochimoto** [comment]
дока есть, контроль не нужен
