### ISSUE TITLE
ns.View: опциональные view

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/noscript#169]
Сейчас сделано так: если `view` указано в `layout` - оно обязательно и если мы не смогли построить ключ для него мы падаем.

У меня уже несколько раз был случай, когда было бы лучше, если бы `view` просто не создавалось, когда недостаточно параметров.

А у вас не было таких случаев?
Может быть не кидать exception, когда `view` не удалось создать?

**Comment by doochik** [comment]
#510
