### ISSUE TITLE
ns.ViewCollection не чистит контейнер детей, когда в ней появляется первый ребенок

### ISSUE THREAD

**Issue by doochik** [yandex-ui/noscript#184]
1. Имеем пустой viewCollection
2. в `ns-view-container-desc` рисуем какую-то заглушку
3. добавляем первый item
4. после перерисовки в контейнере и новый элемент и заглушка

Может быть стоит чистить контейнер или я что-то не так делаю?

@chestozo @edoroshenko

**Comment by chestozo** [comment]
Утеряло актуальность.
