### ISSUE TITLE
Не url-энкодить параметры в generateUrl

### ISSUE THREAD

**Issue by edoroshenko** [yandex-ui/noscript#307]
У меня кастомная структура урлов и символ `/` не является разделителем, а является валидным символом идентификатора сущности.
`generateUrl` самовольно энкодит мои параметры и возвращает искажённые данные.

Я считаю, что энкодить параметры должен сам сервис, если ему это нужно. Например, если у него в значениях параметров цифровые идентификаторы, то ему вообще незачем энкодить параметры.

Давайте оторвём энкодинг?

**Comment by chestozo** [comment]
Сделано в #611
