### ISSUE TITLE
Возможность делать split_id на несколько видов

### ISSUE THREAD

**Issue by bt4R9** [yandex-ui/noscript#324]
Возможно это нужно только мне одному, но всё же.
Есть некоторая боль, связанная с тем, что элемент коллекции я могу проассоциировать только с каким-то одним конкретным видом. В моём случае, я хочу ассоциировать с элементом два вида, например как-то так:
```js
ns.ViewCollection.define('view', {
  split: {
    view_id: {/* кусок лэйаута */}
  }
});
```

**Comment by chestozo** [comment]
Кажется всё это уже появилось, см:
- `split.intoViews`
- `split.intoLayouts`
