### ISSUE TITLE
Опциональные виды

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/noscript#430]
Сейчас такая история: если в layout указан вид - он должен обязательно быть отрендерен.
Это довольно большое ограничение.
К примеру, вот лейаут:
```js
ns.layout.define('photo', {
    'photo': {
        'photo-image': true,
        'photo-edit-controls': true
    }
});
```
Вот эти самые `photo-edit-controls` нужно показывать только автору фотографии и хотелось бы не рендерить этот вид вообще для неавтора.
Но - незя (сейчас).

Никому больше не хотелось такого (чтобы можно было не рендерить виды)?
К примеру, в yate это бы выглядело так:
```html
match .photo ns-view-content {
    match /.views.photo-image ns-view
    if model('photo').authorLogin == model('auth').login {
        match /.views.photo-edit-controls ns-view
    }
}
```

**Comment by doochik** [comment]
#510
