### ISSUE TITLE
Недоделанный update портит результат нового update-а

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/noscript#5]
Бывает такое:
1. перешли мы по ссылке:
1.1. все синхронные блоки подгрузились
1.2. начали грузиться асинхронные
1.3. отрисовалась страница
2. асинхронные блоки не успели догрузиться - а мы уже перешли на новый url!
1.4. Данные для асинхронного блока пришли / запрос зафейлился: мы перерисоввываем страницу (старым update-ом) и затираем уже пришедшие новые данные!!!

Сейчас такое поведение было при листании фоток, когда не приходили комменты: вдруг фотка (текущая) заменялась предыдущей.

Можно сделать через проверку:
`update.id < no.Update.update_counter` - это будет означать, что текущий update - не последний созданный, а значит его не надо дальше выполнять.
Вопрос только: не будет ли у нас когда-то ситуации с несколькими update-ами на одной и той же странице.

**Comment by Katochimoto** [comment]
решено
