### ISSUE TITLE
Редирект на произвольный урл

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#506]
Если зайти по адресу с `#`, например:

```
http://app.com/#/page
```

в современных браузерах `ns` сделает редирект внутри приложения:

```
http://app.com/page
```

Однако, если написать такой адрес:

```
http://app.com/#\/ya.ru
```

то ридирект будет сделан на `http://ya.ru`.

**Comment by chestozo** [comment]
Похоже на критикал

**Comment by vitkarpov** [comment]
Ну да, если все так, то это [открытый редирект](https://www.owasp.org/index.php/Open_redirect)

**Comment by doochik** [comment]
В ns нет поддержки хешей, откуда редирект?

**Comment by vitkarpov** [comment]
Разорбался. Это проектный `history.redirect`. Sorry.
