### ISSUE TITLE
setData with diff

### ISSUE THREAD

**Issue by iEgit** [yandex-ui/noscript#507]
Хочу сделать особый setData, который будет триггерить события только для тех полей, которые были изменены. Это может быть флаг в options или отдельный метод - как будет удобнее.

Использоваться будет следующим образом. 
Есть view, которая должна реагировать на изменения некоторых полей модели, однако не должна перерисовываться полностью. При вызове setData сейчас нет возможности узнать, что именно изменилось, что правильно, так как чаще всего это не нужно. С помощью предлагаемого метода view сможет подписаться только на измененные поля.

**Comment by chestozo** [comment]
У нас есть уже такой (на стороне нашего проекта) - могу показать )

**Comment by chestozo** [comment]
Там есть проблема с производительностью в случае с коллекциями, но для них это можно отключить.

**Comment by iEgit** [comment]
Да, покажи, пожалуйста, имеет смысл вынести.

**Comment by chestozo** [comment]
Вот, что у нас имеется
https://gist.github.com/anonymous/90e6a5a57a7b19d699b5

**Comment by chestozo** [comment]
Да, вторая часть такая:
https://gist.github.com/anonymous/4080e09ab8c408ee81fc

И тогда можно как-то так подписываться на модели для вида:
```js
s.View.define('comments', {
    params: ph.params.commentsViewParams,
    models: ph.utils.nsViewModels({
        'auth': {
            'ns-model-changed': 'invalidate'
        },
        'preferences': {
            'ns-model-changed': {
                '.preferences.preference.[.name == "hide-ads"]': 'invalidate'
            }
        },
        'photo': {
            'ns-model-changed': {
                '.flags.porno': 'invalidate',
                '.flags.blocked': 'invalidate',
                '.askAlbumPassword': 'invalidate'
            }
        },
        'photos-ads-state': {
            'ns-model-changed': {
                '.disabled': 'onAdsDisabledToggle',
                '.reload': 'onAdsReload',
                '.loaded': 'onAdsLoadedChange',
                '.': 'keepValid'
            }
        }
    })
});
```

**Comment by chestozo** [comment]
Основные проблемы в такой схеме:
- на каждый `set` / `beforeSetData` нужно выполнить `this._prevData = _.cloneDeep(this.getData());`
- на событие `ns-model-changed` вызывается `model.hasDataChangedByJpath(jpath)` для каждого jpath, на который подписан хотя бы один вид что тоже может отразиться на производительности.

Но у нас это сейчас в продакшане и сильные тормоза это вроде не вызывает.
Хотя для коллекций мы эту функцию отключили (очень должно выполнялся `_.cloneDeep`).

**Comment by iEgit** [comment]
Да, cloneDeep - это фигово, учитывая, что он по сути не нужен. Попробую в общем сделать PR на эту тему, там посмотрим.

**Comment by chestozo** [comment]
А как иначе ты сделаешь diff?

**Comment by iEgit** [comment]
Исходя из задачи, мне не нужно хранить старые данные. Мне нужны изменения новых данных относительно старых, чтобы вызвать необходимые события. Их можно отловить, пройдясь по данным.

**Comment by chestozo** [comment]
Есть ещё `silent: true` изменения. И если будет цепочка измений - ты их можешь пропустить.

**Comment by chestozo** [comment]
Хотя в моём решении тоже возможно эти изменения не будут отловлены, надо проверить )

**Comment by iEgit** [comment]
не очень понял, если честно. Еще раз, идея такая.
```js
//есть какая-то модель
var model = ns.Model.get('foo', params);
var a = model.getData(); 
// вот ее данные
// a = {
//     foo: 'bar',
//     baz: 'qwe',
//    stable: {}
// } 

// пришли новые данные, я не хочу знать, какие поля изменились, а какие - нет
var newData = {
    foo: 'new bar',
    baz: 'new qwe',
    stable: {}
}

// и мы делаем немного магии
model.setDataDiff(newData, {diff: true})

// что происходит где-то в приложении
model.on('ns-model-changed.foo', function () {
    console.log('should log');
})

model.on('ns-model-changed.qwe', function () {
    console.log('should log');
})

model.on('ns-model-changed.stable', function () {
    console.log('should not log');
})

model.on('ns-model-changed.qwe', function () {
    console.log('should not log');
})

```

**Comment by chestozo** [comment]
А ты уверен, что ты везде можешь подобраться к модели и руками вызвать `setDataDiff `?
А вызовы `setData`, которые делает ns сейчас где-то в недрах себя тебе не интересно diff-ать точно?

**Comment by iEgit** [comment]
1. Я думаю, что такой метод будет обычно вызываться из тех мест, где модель есть и до нее можно легко добаться. Например, в операции: тебе пришли новые данные и ты вызываешь setData у какой-то модели. Откровенно говоря, ты можешь сделать это и сейчас, если точно  знать, какие поля изменились и вручную вызовешь их set. Я как раз хочу избежать такого ручного проставления.
2. Нет, я бы хотел, чтобы вызов этого метода был явным и его использование было осознанным, так как оно отличается от стандартного и требует внимательности разработчика - нужно будет подписаться на все предполагаемые изменения модели и ничего не пропустить.

**Comment by iEgit** [comment]
Вот примерно так я бы хотел, чтобы это было http://repl.it/834/1

**Comment by chestozo** [comment]
Тут вроде бы только diff.

**Comment by iEgit** [comment]
Да, только diff,  который показывает изменения в виде массива. В общем-то по сути остается пройтись по этому массиву и триггерить события модели. Просто хотел наглядно показать, что я имею в виду.

**Comment by shirokoff** [comment]
Я такое для коллекций делал. Тут речь про одинарную модель идёт?

**Comment by chestozo** [comment]
А чем вот этот diff не нравится?
https://gist.github.com/anonymous/90e6a5a57a7b19d699b5#file-model-set-data-js-L4-L6

**Comment by iEgit** [comment]
@chestozo Тем, что он [не показывает изменения](http://underscorejs.org/#isEqual), а просто говорит, разные ли объекты.

**Comment by iEgit** [comment]
@shirokoff Тут вообще не принципиально. Я пока сделал только diff по двум объектам, вернутся по сути jpath'ы изменений. Ничто не мешает пройтись по коллекции в принципе.

**Comment by chestozo** [comment]
@iEgit А, понял. А может заюзать готовый типа https://code.google.com/p/google-diff-match-patch/ ?

**Comment by iEgit** [comment]
@chestozo это же для текста, а не для javascript объектов.

**Comment by chestozo** [comment]
@iEgit точно ) ну тогда https://github.com/benjamine/jsondiffpatch )
Ну можно и своё да.

**Comment by iEgit** [comment]
В общем вот так получилось пока что. Если есть какие-то замечания и дополнения - буду рад обсудить!

 https://github.com/iEgit/noscript-diff

**Comment by edoroshenko** [comment]
С точки зрения api я бы вынес функцию diff в nommon, куда-нибудь рядом с `no.jpath` (подумать надо над названием), т.к. он непосредственно к ns не имеет особого отношения.
А `setDataDiff` можно как-то в виде плагина оформить

**Comment by chestozo** [comment]
@iEgit может закроем? )

**Comment by iEgit** [comment]
да, давай закроем
