### ISSUE TITLE
Определить возможные вариантаы объявления лайаутов

### ISSUE THREAD

**Issue by Katochimoto** [yandex-ui/noscript#510]
Решаем задачи:
- задать для каждого элемента viewCollection собственный layout,
- перестроить layout после загрузки заданных моделей,
- собирать приложение из нескольких layout.

**Comment by Katochimoto** [comment]
Вариант для коллекции из https://github.com/yandex-ui/noscript/issues/509
```js
ns.layout.define('my-layout-collection-item', {
  'my-view-collection-item': {
    'sub-item': {
      'sub-item-async&': {}
    }
  }
});

ns.ViewCollection.define('my-view-collection', {
  split: {
    byModel: 'my-model-collection',
    intoLayout: 'my-layout-collection-item'
  }
});
```
`intoViews` уходит. Элемент всегда задается лайаутом. Если нужен один вид, то это должен быть лайаут с одним видом.

**Comment by Katochimoto** [comment]
Вариант прививки дерева лайаута для любого вида по результатам загрузки моделей.
```js
ns.layout.define('my-view-custom-layout', {
  'sub-item': {
    'sub-item-async&': {}
  }
});

ns.View.define('my-view', {
  patchLayaut: function() {
    // тут уже есть данные моделей
    // выбираем название нужного лайаута на основе данных моделей
    return 'my-view-custom-layout';
  }
});
```

**Comment by doochik** [comment]
1. Я не вижу реального применения для `patchLayout`. Привидите, плиз, примеры
2. @Katochimoto и @shirokoff опишите примерно как вы видите работу раскрытия писем в тредах в 3p и раскрытие писем в списке. Ведь мы ради этого все и делаем.

**Comment by doochik** [comment]
Описал проблему автораскрытия древовидных списков в #511

**Comment by doochik** [comment]
Пока у нас складывается такой вариант: `split.intoViews` заменем на `split.intoLayout`
`split.intoLayout` строка или функция, все аналогично `split.intoViews`

Для сменя layout в view делаем метод `patchLayout`, который будет вызываться примерно вот тут https://github.com/yandex-ui/noscript/blob/e1ae97eac2f0b4319309e590f436cbc96293a902/src/ns.view.js#L658 перед проходом дереву и изменять дерево при необходимости.

Моменты, которые меня смущают:
 1. Размазывание раскладки страницы между ns.layout и ns.View. Отсюда получается
 2. В layout можно указать одно, а на самом деле отрисуется другое, потому что вид это переопределит

**Comment by doochik** [comment]
Нашли проблему.

Есть layout
```
app
  v1
  v2
```

У `v1` есть
```
patchTree: function() {
  if (this.getModel('state').isGood()) { 
     return 'sublayout-1'; 
  } else {
     return 'sublayout-2';
  }
}
```

При первом проходе patchTree вернет sublayout-2 (потому что данных еще нет и мы уйдет в else) и будут запрошены модели для видов из sublayout2. А при втором проходе вернет sublayout1 и модели будут запрошены оттуда.

Кажется, что правильным вариантом будет не ходить вниз по patchLayout до тех пор, пока у этого вида не окажутся валидные модели. Примерный код:
```
function getRequestView() {
.... 

if (view.isModelsValid()) {
   // можно пропатчить и посмотреть что получится
   view.patchTree(...)
} else {
   // надо запросить модели для этого вида
   result.sync.push(view)   
}

// спускаемся дальше по определенному в данный момент дереву
...
}
```

**Comment by doochik** [comment]
ns.update соответственно будет ходить по дереву до тех пор пока не надо будет ничего запрашивать

**Comment by edoroshenko** [comment]
> Кажется, что правильным вариантом будет не ходить вниз по patchLayout до тех пор, пока у этого вида не окажутся валидные модели

Тогда мы лишаем себя возможности запросить все модели и из корневого layout и из вложенных layout одной пачкой.

Лёш, мне кажется, что то, что ты описал - это не проблема, а неоптимальная конструкция, которую можно создать. А можно и не создавать :)

**Comment by edoroshenko** [comment]
Мне api видится таким

```js

    ns.View.define('idViewCollection', {
        models: {},
        events: {},
        layout: 'idLayout' | function(paramsRewrited) {}
    });

    ns.View.define('idViewCollection', {
        models: {},
        events: {},
        split: {
            byModel: 'm1',
            intoLayouts: 'idLayout' | function(paramsRewrited) {},
            intoViews: 'idViewItem' | function(paramsRewrited) {}
        }
    });
```

В чём отличия:
1. В моей картинке кастомные layout'ы нужно поддерживать не только у VC, но и у обычных видов
2. Нужно оставить возможность указания одиночного вида в VC. Чтобы не усложнять код, можно просто автоматом создавать layout с одним видом, это очень просто

**Comment by doochik** [comment]
1. Это есть и моей картине, потому что `patchLayout` есть у всех
2. Да, можно как алиас оставить

> Лёш, мне кажется, что то, что ты описал - это не проблема, а неоптимальная конструкция, которую можно создать. А можно и не создавать :)
Вообще эта штука для тебя делалась :)
У тебя же по логике все равно надо запрашивать модели, чтобы понять какой layout будет дальше. Так зачем идти дальше если layout неивестен ?

**Comment by edoroshenko** [comment]
Он может быть и известен. Моделей нет - нарисовали заглушку. В моделях ошибки - нарисовали сообщение

**Comment by edoroshenko** [comment]
Я если честно, до конца не понял, почему тебя беспокоит эта ситуация. Запросятся сначала одни модели, потом другие. Это может быть даже полезным

**Comment by doochik** [comment]
> Моделей нет - нарисовали заглушку.

Не так. Моделей нет -> запросили -> пришли еще раз.
Из-за многопроходности я как раз и не вижу смысла ходить в них заранее

**Comment by edoroshenko** [comment]
Понял тебя, согласен

**Comment by doochik** [comment]
Let's rock!
https://github.com/yandex-ui/noscript/pull/514

**Comment by doochik** [comment]
Атас, ребята! Коллекции заработали! Можно смотреть на API и комментировать.
Это пока черновой вариант, все тесты проходят кроме двух edge cases
