### ISSUE TITLE
Проблема деревьев после #510

### ISSUE THREAD

**Issue by doochik** [yandex-ui/noscript#511]
Сейчас элементы коллекции не входят в layout, поэтому не запрашивают свои модели. Раскрытие деревьев делается вручную.
После #510 элементы войдут в layout и будут полноправнями участниками процесса. Это приведет к проблеме деревьев, которые будут автоматически отрисованы до конца.

Пример
```
vc-level0 (mc-level0)
  vc-level0-item (mc-level0-item)
  vc-level1 (mc-level0-item, mc-level1)
    vc-level1-item (mc-level1-item)
    vc-level1-item (mc-level1-item)
  vc-level0-item (mc-level0-item)
```

Как работает сейчас: update запрашивает `mc-level0`, сплитит коллекцию на `mc-level0-item` и строить по ней `vc-level0-item`. `mc-level1` при это не запрашивает, т.к. `vc-level1` не входит в layout. `vc-level1`, например, рисует кнопку "раскрыть", которая делает `this.update()` и раскрывает коллекцию внутри себя по действию пользователя.

Как будет работать:  update запрашивает `mc-level0`, сплитит коллекцию на `mc-level0-item` и строить по ней `vc-level0-item`. При втором проходе будет запрошена `mc-level1`, произведен сплит и в layout появятся `vc-level1-item`.

Чтобы избежать проблемы раскрытия всего дерева у меня есть идея "отложенной модели" (дурацкое название, да :)    https://github.com/yandex-ui/noscript/tree/view-with-delayed-models
Суть ее в том, что зависимость `vc-level1` от `mc-level1` объявляется как "отложенная". 
```js
ns.View.define('vc-level1', {
  models: {
    'mc-level0-item': true,
    'mc-level1': 'delayed'
  }
})
```
Отложенная модель не участвует в зависимостях и учете валидности, соответственно не запрашивается. Этот механизм предотвращает отрисовку полного дерева, а рисует его до нужного уровня.
Для управления есть два метода `enableModel('mc-level1')` и `disableModel('mc-level1')`.
После нажатия кнопки раскрыть надо сделать
```js
this.enableModel('mc-level1');
this.update(); // или ns.page.go()
```
После нажатия кнопки закрыть надо сделать
```js
this.disableModel('mc-level1');
this.update(); // или ns.page.go()
```

**Comment by doochik** [comment]
@shirokoff @Katochimoto @chestozo @edoroshenko

**Comment by edoroshenko** [comment]
Мне кажется, этим нужно управлять вручную.
Концептуально я представляю это так: есть у тебя модель состояния, в которой хранится "раскрыто/свёрнуто". В виде у тебя есть функция, в которой ты в зависимости от этого признака можешь вернуть либо один layout, либо другой

**Comment by doochik** [comment]
Ага, т.е. вместо `vc-level1` мы делаем `vc-level1-wrapper`, внутри которого уже при необходимости появляется `vc-level1`. Годный вариант.

**Comment by doochik** [comment]
Тогда надо возвращаться в #510 и сделать API для смены layout

**Comment by edoroshenko** [comment]
Зачем wrapper?

**Comment by edoroshenko** [comment]
ах ты ж, и правда тут либо wrapper, либо нужно что-то с моделями придумывать

**Comment by edoroshenko** [comment]
у тебя, Лёш, уже был заход на обязательные/не обязательные модели, который мы потом выпилили с декларативной подпиской на события. Может стоит ещё разой обдумать эту тему...

**Comment by doochik** [comment]
ну вот enable/disable как раз простой вариант реализации такой идеи

**Comment by edoroshenko** [comment]
Только придётся в декларации совмещать дофига всего
 - подписку на события моделей
 - понимание, нужно ли её учитывать в общих механизмах. Причём тут захочется тоже где-то воткнуть функцию
 - есть ещё #508 , которая тоже выглядит полезной и тоже декларируется там же

**Comment by doochik** [comment]
Да, есть некоторые нюансы, первые 2 у меня решены

**Comment by edoroshenko** [comment]
а как первые 2 решены?

**Comment by doochik** [comment]
disableModel убирает все подписки и выключает модель из зависимостей

**Comment by edoroshenko** [comment]
ну так ты 2 признака заключаешь в одну настройку, лишаясь возможности управлять или по отдельности

**Comment by doochik** [comment]
Поэтому это и "простой вариант" :)

**Comment by edoroshenko** [comment]
Типа самый общий случай мог бы выглядеть примерно так:
```
ns.View.define('view', {
    models: {
        m1: {
            select: function(e) {},
            fetch: function(e) {},
            events: {
                'ns-model-changed': 'keepValid'
            }
        }
    }
})
```

**Comment by chestozo** [comment]
Почитал тредик.

Имею добавить:
- ручная подписка вида на модель была бы полезной в любом случае. К примеру, вид грузит вначале базовые данные, а затем мы руками подгружаем модель и хотим на неё точно также подписаться.
- вариант включить / выключить модель - с виду кажется, это работает только на 1 уровень вложенности, т.е. элемент коллекции разворачивает свой лейаут и дальше уже этот лейаут никуда не разворачивается - так? если так, это довольно ограниченная штука получается
- не очень понял, зачем может потребоваться `disableModel`, ведь эти данные уже использовались для отрисовки вида, зачем их отключать?

Может нам ещё раз встретиться нужно? )

**Comment by doochik** [comment]
@chestozo да, #510 решает проблему более красиво
