### ISSUE TITLE
В асинхронные вьюхи не попадают дополнительные параметры из update()

### ISSUE THREAD

**Issue by shirokoff** [yandex-ui/noscript#521]
Есть лейаут:
```
    ns.layout.define('message-opened', {
        'message': {
            'message-head': {},
            'message-body&': {}
        }
    });
```
Запускаю апдейт с дополнительным параметром ```view.update({_yateModule: 'message'})```.
В конечном итоге дополнительный параметр не доезжает до vMessageBody.

**Comment by chestozo** [comment]
:+1:

**Comment by edoroshenko** [comment]
:+1:

**Comment by shirokoff** [comment]
Тесты сделаю, когда @doochik и @Katochimoto пальцы поставят.
