### ISSUE TITLE
Научить patchLayout чистить лейаут

### ISSUE THREAD

**Issue by shirokoff** [yandex-ui/noscript#523]
Сейчас patchLayout умеет возвращать: 
  * строку с лэйаутом – заменяет лейаут
  * значение приводимое к false – ничего не делает

Надо научиться удялть вложенный лейаут.

Возможно имеет смысл сделать так, что если patchLayout возвращает null, тогда надо чистить лейаут с последующим удалением вложенных вьюх.

**Comment by shirokoff** [comment]
@doochik @Katochimoto

**Comment by doochik** [comment]
Туда же https://github.com/yandex-ui/noscript/blob/issue-510-dymanic-layouts/src/ns.view.js#L681
