### ISSUE TITLE
Нет дефолтных `jpathItems` модели-коллекции, если не указан `split.items`

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#540]
Если не указать `info.split.items` или `info.jpathItems` в декларации модели-коллекции, то дефолтный `jpathItems` (`'.items'`) установлен не будет.

Кажется, проблема в [некорректном условии](https://github.com/yandex-ui/noscript/blob/master/src/ns.modelCollection.js#L42).

**Comment by doochik** [comment]
Можешь более детально описать проблему или прямо тест сделать?

**Comment by vitkarpov** [comment]
```
ns.Model.define('todos', {
  split: {
    model_id: 'todo'
    params: {
      id: '.id'
    }
  }
})
```

С сервера приходит структура `{ items: [{id: '1'}, {id: '2'}, ..., {id: 'n'}] }`.
Ожидаю, что модель-коллеция по дефолту возьмет `items` и распарсит. Сейчас ошибка.

Давай напишу тест на это дело, действительно, и поправлю?

**Comment by vitkarpov** [comment]
Посмотрел внимательно: кажется, что такого просто нет. Написал тест в пул реквесте.

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript/pull/541
