### ISSUE TITLE
[ns.View] Бросать исключение, если меняются дети

### ISSUE THREAD

**Issue by doochik** [yandex-ui/noscript#542]
Чтобы избежать странных ошибок и помочь разработчику, надо бросать исключение, если у обычного вида меняются дети.

Тест простой:
```
ns.layout.define('app1', {
   'view1': {
     'view2': {}
   }
});

ns.layout.define('app2', {
   'view1': {
     'view3': {}
   }
});

var view = ns.View.create('app')
view.updateByLayout('app1').then(function() { 
  return view.updateByLayout('app2');
})
```

Тут хистрость в том, что `view3` не появится, потому что `view1` не знает куда его добавлять

**Comment by vitkarpov** [comment]
@chestozo Написал на это дело кейс — https://github.com/yandex-ui/noscript-demo/tree/issue-542 Описал как раз ситуацию, близкую к тому, что было у нас в приложении.

Сделаю пул в ns с правильным эксепшеном для такой ситуации.
