### ISSUE TITLE
[ns.request] Не реджектится промис, если при запросе произошла ошибка

### ISSUE THREAD

**Issue by i2r** [yandex-ui/noscript#556]
Вот в этом месте, кажется, нужно выполнять ``reject``: https://github.com/yandex-ui/noscript/blob/master/src/ns.request.js#L266-L273

Иначе у ``ns.forcedRequest`` (да и просто ``ns.request``) не вызовется ``fail()``, например, при закрытии соединения по таймауту.

**Comment by doochik** [comment]
Подебажили с @i2r. Баг на их стороне.
