### ISSUE TITLE
Не обрабатывать ссылки с атрибутом `target`

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#574]
Сейчас не обрабатываются ссылки со значением `_blank` атрибута `target`.

Иногда хочется намеренно перезагрузить страницу, в том же окне, при клике на ссылку: было бы круто, не обрабатывать так же значение `_self` для атрибута.

Сейчас приходится делать переход js-ом.

**Comment by doochik** [comment]
Да, только кажется, что вообще не надо обабытвать ссылку, если у нее есть атрибут `target`. Что думаешь?

**Comment by vitkarpov** [comment]
> Да, только кажется, что вообще не надо обабытвать ссылку, если у нее есть атрибут target

Ага, именно так. Вдруг у кого-то есть айфреймы на сайтах и вдруг этому кому-то захочется загружать новые документы по указанным ссылкам в них — всякое бывает :)
