### ISSUE TITLE
Перерисовки вьюшек на основе virtual-dom

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#576]
Коллеги!

Есть ли сейчас в планах заходы/мысли о том, чтобы сделать перерисовки на основе виртуального дома? Есть несколько реализаций самого алгоритма сравнения/вставки и АПИ для описания дерева, например, https://github.com/Matt-Esch/virtual-dom

Как я себе представляю, что можно сделать:

- у нас есть скомпилированные шаблоны `yate`, которые после применения дают строки html
- можно сделать транслятор — html -> virtual-dom: либо на уровне `ns`, либо, что еще лучше, написать плагин для `yate`, который позволяет получить скомпилированные шаблоны сразу в описании виртуального дерева.
- `ns` выполняет [`diff`](https://github.com/Matt-Esch/virtual-dom#diff-computation) и [`patch`](https://github.com/Matt-Esch/virtual-dom#patch-operations) при перерисовках

**Comment by doochik** [comment]
Да, у меян был заход на react, но я его так и не добил.
Вообще, идея богатая и можно ее пробовать.

**Comment by vitkarpov** [comment]
> Да, у меян был заход на react

а заход на что именно? я имею ввиду, что есть два подхода:

- использовать полностью реакт, по сути, как замену шаблонизатору (плохо, потому что придется переписать все шаблоны в проекте)
- использовать механизм виртуального дома, который есть в реакте (по сути, то о чем я написал в описании)

**Comment by doochik** [comment]
У меня был заход не на замену, а на встраиваение, чтобы плавно переписаться с ятя на react.
С одной стороны, мне не хочется половинчатых решений (как virtual dom), с другой - переписаться на реакт правда дорого.

В целом, я не против и можно попробовать прикрутить либу

**Comment by vitkarpov** [comment]
> не на замену, а на встраиваение

чтобы можно было одно время поддерживать оба вида шаблонов и плавно переписывать старые?

**Comment by doochik** [comment]
Ага. У меня была мысль начинать с кончиков дерева и постепенно подниматься вверх до корня
