### ISSUE TITLE
[ns.router] Экранирование параметров при генерации урла

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#584]
`ns.router.generateUrl` по умолчанию экранирует значения параметров при формировании урла. Это не всегда бывает удобно.

Хочется дать возможность разработчику отключить эту возможность (сделать ее опциональной), тогда при необходимости не придется делать `decodeURIComponent` при каждом вызове функции.

**Comment by vitkarpov** [comment]
@doochik @Rebulus

**Comment by Rebulus** [comment]
https://github.com/yandex-ui/noscript/pull/397 - тут был добавлен encode для параметров. В этом ишью уже обсуждали https://github.com/yandex-ui/noscript/issues/307 необходимость в автоматическом `encode`. Я за то, чтобы отдать это приложению или уметь управлять этим.

**Comment by vitkarpov** [comment]
Вот здесь предлагалось АПИ https://github.com/yandex-ui/noscript/issues/307#issuecomment-51963600 — можно что-то в этом духе сделать. Вроде норм выглядит.

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript/pull/611

**Comment by vitkarpov** [comment]
Done
