### ISSUE TITLE
generateHTML возвращает лишнюю обёртку

### ISSUE THREAD

**Issue by alexeyten** [yandex-ui/noscript#585]
При серверном рендеринге `update.generateHTML` возвращает строку завёрнутую в `<div class="ns-root">`

//cc @vitkarpov

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript/pull/587

**Comment by vitkarpov** [comment]
Done

**Comment by Katochimoto** [comment]
Ломает почту.
Причина `ns.renderNode`. Использует измененный метод `html2node`.
И широко применяется для рендеринга конкретный мачей. Как правилоя для рендера островных окон в связке, например
```js
var popup = nb.block(ns.renderNode({}, 'js-ckeditor-mailpastefromword', 'ckeditor'));
```
После фикса nb.block ничего не возвращает, так как появляется дополнительный враппер.

**Comment by Katochimoto** [comment]
и вообще, выполняя `ns.renderNode` я хочу получить то что в маче рендерится.
а мне подсовывают фейковый враппер!

**Comment by vitkarpov** [comment]
обсудили с @Katochimoto 

В итоге, нужно поправить `ns.renderNode`, чтобы возвращал саму ноду, без обертки, которую добавляет `ns.html2node`, а так же написать на это дело тест, чтобы на будущее зафиксировать необходимое поведение.

**Comment by vitkarpov** [comment]
Сделаем отдельным пулом

**Comment by Katochimoto** [comment]
https://github.com/yandex-ui/noscript/pull/596
