### ISSUE TITLE
Нет поддержки jpathItems при установке данных в коллекцию

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#595]
Кажется, при `setData` смотрим только на `split`, не учитывая `jpathItems`, как в `getData`. В итоге, коллекция не сплитится на модельки.

https://github.com/yandex-ui/noscript/blob/088782ceb8215beffc5055d3241c217bdf094aac/src/ns.modelCollection.js#L107

Сделаю пул с тестом на это.

**Comment by vitkarpov** [comment]
@Katochimoto @chestozo или он и не должен, всмысле, `jpathItems` нужен как раз когда коллекция наполняется вручную?

**Comment by chestozo** [comment]
Кажется, мы не пользуемся.
Но логично, чтобы `jpathItems` использовался везде, где и `split.items`.

**Comment by vitkarpov** [comment]
Я просто в документации увидел:

> Если модель наполняется вручную, то split можно не указывать, а указать флаг isCollection === true. Для таких колекций так же можно указать jpath, по которому будет лежать коллекция - jpathItems (по умолчанию, .items).

Честно говоря, не пойму для чего был введен `jpathItems`.
