### ISSUE TITLE
Баг с сылками в IE11 

### ISSUE THREAD

**Issue by km256** [yandex-ui/noscript#604]
Есть вот такой баг в ie11
https://connect.microsoft.com/IE/Feedback/Details/1426119
Из-за которого некорректно обрабатываются клики по ссылкам вот здесь:
https://github.com/yandex-ui/noscript/blob/v0.8.5/src/ns.history.js#L87

Думаю стоит поддержать случай, когда `hostname` внезапно оказывается пустым

**Comment by vitkarpov** [comment]
```js
var a = document.createElement("a");
a.href = "somepath/index.html";
console.log("Protocol -> " + a.protocol);
console.log("Hostname -> " + a.hostname);
console.log("Port -> " + a.port);
console.log("Pathname -> " + a.pathname);
```

В ИЕ11 `hostname` и `protocol` — пустые

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript/pull/609

**Comment by vitkarpov** [comment]
Done
