### ISSUE TITLE
добавить опциональный параметр в getModelData

### ISSUE THREAD

**Issue by iEgit** [yandex-ui/noscript#605]
Было бы удобно вторым параметром указывать jpath, чтобы можно было сразу получать данные из модели. Аналогично уже сделано в [noscript-react](https://github.com/yandex-ui/noscript-react/blob/master/src/ns.viewReactMixin.js#L173).

**Comment by i2r** [comment]
Но всегда можно дописать `.get(jpath)`?

**Comment by iEgit** [comment]
можно, предлагаю просто более короткий вариант.

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript/pull/606

**Comment by vitkarpov** [comment]
Done
