### ISSUE TITLE
[ns.Box] Динамическая вставка нод в боксе в неправильном порядке

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#614]
Лейаут:

```js
'wrapper@': function() {
  return {
    v1: true,
    v2: true
  }
}
```

Обычно в боксе появляются ноды в том же порядке, в каком они были объявлены в лейауте в объекте, однако, бывает так, что сперва идет v2.

Кажется, дело в том, что мы [итерируемся по ключам в объекте(лейаут бокса)](https://github.com/yandex-ui/noscript/blob/master/src/ns.box.js#L277) и показываем/скрываем ноды — однако, `for..in` по ключам не гарантирует порядок (хотя в большинстве случаев и ок).

**Comment by chestozo** [comment]
Что-то мне кажется я такое делал и даже тесты писал про то, что виды должны быть в правильном порядке, помню помню.
А тест сможешь забубенить?

**Comment by vitkarpov** [comment]
> Что-то мне кажется я такое делал

А удалось воспроизвести в тесте, в итоге? Мы просто видели такое в приложении, но воспроизводится очень редко.

**Comment by chestozo** [comment]
Вот, нашёл - фиксилась последовательность видов внутри бокса #499

**Comment by chestozo** [comment]
#499 #502

**Comment by vitkarpov** [comment]
Хм. Судя по всему, теперь должно работать как надо.

**Comment by chestozo** [comment]
По идее так уже довольно давно работает (с Feb 3, 2015), а у тебя проблемы давно эти были?

**Comment by vitkarpov** [comment]
Да, скорее всего, я нашел какой-то старый TODO в коде просто.
