### ISSUE TITLE
Неконсистентость при работе с параметрами

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#617]
Столкнулся со следующей некосистентностью при работе с параметрами синхронной и асинхронной вьюшек.

```js
'v-1&': {
    'v-2': true
}
```

`v-1` в своей декларации доопределяет параметры через `params`.

В случае асинхронной `v-1` вьюшка `v-2` получает все параметры от `v-1` (и прокидывает их вниз по дереву, если там есть еще виды).

В случае синхронной `v-1` **вьюшка `v-2` получает только глобальные параметры апдейта**.

**Comment by vitkarpov** [comment]
@chestozo @Katochimoto

**Comment by vitkarpov** [comment]
Вообще, я столкнулся с тем, что хочется получить параметры от родительской вьюшки в синхронном апдейте. Пример простой:

```js
'v-1': {
  'v-2': true
}
```

'v-1' — вьюшка в коллекции, она вычисляет дополнительный параметр на основании того, что получила в свои параметры от модели.

`v-2` хочет использовать этот параметр (зависит от такой же модели, которая требует этот параметр), однако — она не получит его в случае синхронного адпейта.

В итоге, мне приходится вычислять этот параметр снова и снова во всех вложенных вьюшках.

Как быть?

**Comment by vitkarpov** [comment]
Можно сформулировать еще проще: `v-1`, как элемент в коллекции, зависит от соответствующей модельки в коллекции, а если хочешь поставить в зависимость эту же модельку для `v-2`?

Сейчас `v-2` при апдейте не может понять какой экземпляр ей брать, потому что получает только глобальные параметры, но не параметры соответствующей модельки.

**Comment by vitkarpov** [comment]
Пока приходят в голову всякие решения «в лоб», типа, флага `leakParamsIntoNestedViews` для вьюшки и все такое

**Comment by chestozo** [comment]
А что у v1 и v2 в декларации?
`params` / `params+` / `params-` ?

**Comment by vitkarpov** [comment]
Просто `params`. Сделаю пример небольшой в `noscript-demo`.

**Comment by vitkarpov** [comment]
Написал на это дело тест-кейс в noscript-demo ↑

Кажется, какой-то минорный кейс, т.к. глобальные параметры дочерние вьюшки по-прежнему получают, а на параметры от родителя — не должны рассчитывать.
