### ISSUE TITLE
В ИЕ11 не обрабатывается переход по относительной ссылке в _onAnchorClick

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#628]
https://github.com/yandex-ui/noscript/blob/v0.8.7/src/ns.history.js#L86

В ИЕ11 нет `target.protocol` для относительных ссылок. Соответственно, не обрабатываем переход через ns.page.go.

**Comment by iEgit** [comment]
> В ИЕ11 нет target.protocol для относительных ссылок

Созданных через `document.createElement`
