### ISSUE TITLE
Падает ns.page.go на сервере

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript#636]
Нет `ns.page.block` в серверном бандле, а при вызове `ns.page.go` происходить обращение к `ns.page.block.check` — получаем ошибку.

**Comment by vitkarpov** [comment]
Мне кажется, что на сервере и не предполагалось использование `ns.page.go`. Т.е. можно только создавать экземпляр апдейта и запускать его руками с нужными параметрами.

@doochik @chestozo что думаете, может помнит кто-нибудь эту историю?

Конкретно столкнулся с тем, что в приложении используется `ns.page.go` на уровне лейаута:

- пришли в лейауте А в бокс
- проверили, что в модельке ошибка и нужно показывать страницу ошибки
- сделали в лейауте ns.page.go на специальный урл для перехода в лейаут B

Возможно, так делать вовсе нельзя и надо это править на уровне приложения (например, запретив использование ns.page.go в лейауте, а создавать новый экземпляр апдейта), а не тулить `ns.page.go` в серверный рендеринг?

**Comment by chestozo** [comment]
> Конкретно столкнулся с тем, что в приложении используется ns.page.go на уровне лейаута:

да, это нехороший паттерн.

> например, запретив использование ns.page.go в лейауте, а создавать новый экземпляр апдейта

не, в лейауте - только лейаут, никакие ns.page.go / ns.Update.

**Comment by vitkarpov** [comment]
Ага, понял. А зачем тогда `ns.page` и `ns.page.history` нужны в серверном бандле?

**Comment by chestozo** [comment]
Хороший вопрос )

**Comment by vitkarpov** [comment]
Ладно, это уже другой вопрос. Этот issue тогда закрываю — в приложении выпиливаю `ns.page.go` в лейауте.

**Comment by chestozo** [comment]
👍
