### ISSUE TITLE
Унести ns.VERSION в build шаблоны

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/noscript#637]
Предлагаю не использовать borschik в src файлах noscript-а.

Давайте унесём вот это
`ns.VERSION = 'borschik:include:../.version';`
в шаблонные файлы
https://github.com/yandex-ui/noscript/blob/master/build/src.client.js#L9
https://github.com/yandex-ui/noscript/blob/master/build/src.server.js#L7

Может быть вообще стоит создать `ns.version.js`?

**Comment by vitkarpov** [comment]
done https://github.com/yandex-ui/noscript/pull/641
